files = ["icon_1_port/chipscope_icon_1_port.ngc",
	"icon_1_port/chipscope_icon_1_port.vhd",
	"icon_2_port/chipscope_icon_2_port.ngc", 
	"icon_4_port/chipscope_icon_4_port.ngc", 
	"icon_4_port/chipscope_icon_4_port.vhd",
	"icon_7_port/chipscope_icon_7_port.ngc", 
	"icon_7_port/chipscope_icon_7_port.vhd", 
	"icon_8_port/chipscope_icon_8_port.ngc",
	"icon_8_port/chipscope_icon_8_port.vhd",
	"ila/chipscope_ila.ngc", 
	"ila/chipscope_ila.vhd", 
	"ila/chipscope_ila_8192.ngc",
	"ila/chipscope_ila_8192.vhd"]
