#!/bin/bash

EXPECTED_ARGS=1

# Test for parameter presence

: ${1?"Usage: $0 <bistream>"}

BITSTREAM=$1

# Write the commands to a temporatry file

cat > .impact_batch << EOF
setMode -bscan
setCable -port auto
identify
assignFile -p 2 -file ${BITSTREAM}
program -p 2
closeCable
quit
EOF

impact -batch .impact_batch
rm .impact_batch
